/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddChapterDialog: typeof import('./src/components/addChapterDialog.vue')['default']
    AddCourseDialog: typeof import('./src/components/addCourseDialog.vue')['default']
    AddMaterialDialog: typeof import('./src/components/addMaterialDialog.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
